"""fix-fk-datatypes-only

Revision ID: c7ed5ef28348
Revises: 346fd7b729b2
Create Date: 2026-02-04 17:23:33.966197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ed5ef28348'
down_revision: Union[str, Sequence[str], None] = '346fd7b729b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointments', 'payments', ['payment_id'], ['id'])
    op.alter_column('doctor_slots', 'appointment_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_unique_constraint(None, 'doctor_slots', ['appointment_id'])
    op.create_foreign_key(None, 'doctor_slots', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(op.f('laboratories_owner_user_id_key'), 'laboratories', type_='unique')
    op.drop_constraint(op.f('laboratories_owner_user_id_fkey'), 'laboratories', type_='foreignkey')
    op.drop_column('laboratories', 'owner_user_id')
    op.drop_constraint(op.f('pharmacies_owner_user_id_key'), 'pharmacies', type_='unique')
    op.drop_constraint(op.f('pharmacies_owner_user_id_fkey'), 'pharmacies', type_='foreignkey')
    op.drop_column('pharmacies', 'owner_user_id')
    op.create_unique_constraint(None, 'wallet_transactions', ['appointment_id'])
    op.create_foreign_key(None, 'wallet_transactions', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_constraint(None, 'wallet_transactions', type_='unique')
    op.add_column('pharmacies', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pharmacies_owner_user_id_fkey'), 'pharmacies', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('pharmacies_owner_user_id_key'), 'pharmacies', ['owner_user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('laboratories', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('laboratories_owner_user_id_fkey'), 'laboratories', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('laboratories_owner_user_id_key'), 'laboratories', ['owner_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'doctor_slots', type_='foreignkey')
    op.drop_constraint(None, 'doctor_slots', type_='unique')
    op.alter_column('doctor_slots', 'appointment_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # ### end Alembic commands ###
